### ISSUE TITLE
Merge position into Contact

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudbooks-Github/EasyCloudBooks#11]
Merge Position to Contact on Company Page 
Changes for Contact window

1. Add "Default" button to select Default Contact.
2. Add "Position" column.

<img width="1440" alt="Contact" src="https://github.com/EasyCloudbooks-Github/EasyCloudBooks/assets/46813198/4e12f5be-d115-4e86-bbd8-c500efc89219">

**Comment by dharmendraecb** [comment]
![Image](https://github.com/EasyCloudbooks-Github/EasyCloudBooks/assets/46588108/44712a81-b13b-4675-aced-8a4e7454b5f9)
