### ISSUE TITLE
Create Templet For Easycloudebooks.

### ISSUE THREAD

**Issue by ecb-mahesh** [EasyCloudbooks-Github/EasyCloudBooks#21]
Create different different Sections In Home page

**Comment by ecb-kunal** [comment]
Theme Home Page Completed.



![Image](https://github.com/EasyCloudbooks-Github/EasyCloudBooks/assets/145744900/6bc59372-313f-4131-8d73-b6b5954b3ecb)

**Comment by ecb-kunal** [comment]
Create Templet About Page

**Comment by ecb-kunal** [comment]
Create Service Page

**Comment by ecb-kunal** [comment]
Create Team Page



![Image](https://github.com/EasyCloudbooks-Github/EasyCloudBooks/assets/145744900/538d9fc9-4f69-4c46-b3be-207e2c271a42)

**Comment by ecb-kunal** [comment]
Create The Blog Page

**Comment by ecb-kunal** [comment]
Create The Career Page...

**Comment by ecb-kunal** [comment]
Create The Contact Us Page...


![Image](https://github.com/EasyCloudbooks-Github/EasyCloudBooks/assets/145744900/c46e7000-1095-4bbc-ad5b-042d644e3a7f)

**Comment by ecb-kunal** [comment]
Create The Privacy Policy Page...

**Comment by ecb-kunal** [comment]
Create The Refund Policy Page...

**Comment by ecb-kunal** [comment]
Create The Terms & Conditions Page...



![Image](https://github.com/EasyCloudbooks-Github/EasyCloudBooks/assets/145744900/ac198a99-8a4f-45aa-a910-bf7d2a9d6ccd)
