### ISSUE TITLE
Email Clients

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudbooks-Github/EasyCloudBooks#75]

**Comment by sureshsirvi** [comment]
1. Trial period ends. 
2. New Pricing ... 
3. New Module Release..
4. Selected users only.. special mail.

**Comment by sureshsirvi** [comment]
email sent on 3rd October 2024 from support mail id

Exciting New Updates & Important Pricing Change!

Dear Kishor Choudhary,


We hope this message finds you well. At EasyCloudBooks, we are constantly striving to improve our services and provide more value to your practice. As part of this effort, we are excited to announce the release of the following new modules, effective from 1st October 2024:


These new modules have been made available for trial in previous months [i.e. August and September] and have been officially launched from 1st October 2024. Following this period, there will be an adjustment in your subscription charges to reflect these new additions.


Important Notice:

If you prefer not to continue with these opted new modules and wish to avoid additional charges, you have the option to opt out on or before 15th October 2024. Please note, if we do not hear from you by this date, the new pricing will take effect, and the modules opted will remain active in your account.


To opt out, Go to “Setting —> Other Setting —-> Module” opt-out the modules or contact our support team at support email: [support@easycloudbooks.com](mailto:support@easycloudbooks.com)  or Mobile: +91 99747 75018.


We appreciate your trust in EasyCloudBooks, and we are confident that these new modules will significantly enhance your experience with us.


Highlights of Features of new Modules:


WhatsApp API Integration

Send Whatsapp messages using Automation.

Send and Receive Documents on Whatsapp.

Create your own Whatsapp template messages.

Easy Access of Contacts, Companies and Projects from WhatsApp.

Multiple users can send whatsapp messages using the same number.

Multiple users can communicate with a single contact as group communication.

User wise communication history.


Income Tax Module


Import Company Using Credentials

Credential Management


Income Tax Return Management

ITR Return Filed Status

Default ITR Returns

Refund Status

EVC Status

Digital Signature Status

Adhar Link Status

Revised ITR Return Status

Income Head wise Computation of Income 3 years Comparison

ITR-V PDF Download

Intimation u/s 143(1) PDF Download


Audit Management

Auditor Wise Audit Reports

Clause Wise Audit Reports

Form 3CD PDF Downloads

Audit Reports PDF Attachments Downloads [P&L and Balance Sheet Etc.]


e-proceedings Management

Date Wise Notices and PDF Downloads

Datewise Replies Attachments PDF Downloads


Refund Management

Refund Failed

Refund Paid

Refund Reissue Status


Demand Notice Management

Demand Notices PDF Downloads

Demand Notices Replies Attachments PDF Downloads

Demand Status


Other Statistic Reports

ITR Return Missed Reports

ITR Return Filed After Due Dates

ITR Return Form Wise Filed Reports

ITR Return Month Wise Filed Reports

Types of Person Wise Companies

Top 5 Tax Paid Companies

Top 5 Interest Paid Companies


Auto Pilot Mode

Auto Service Assign to Companies

Auto Project Create for Recurring Services

Auto Project Create and Links with Demand Notice, e-proceedings Notices, Refund Failure Etc. for Companies


GST Module


Import Company Using GSTIN

Credential Management


GSTN Company Auto Management

Monthly Companies Reports

Quarterly Companies Reports

Composition Companies Reports

Cancelled GSTIN Reports

Suspended GSTIN Reports

Types of Person Wise Clients

State Wise Companies

e-Invoice Opted GSTIN


GST Return Management

Monthly Return Status

Quarterly Return Status

Annual Return Status


Auto Pilot Mode

Auto Service Assign to Companies

Auto Project Create for Recurring Services

Auto GSTR Return frequency Update


TDS Module


Credential Management


TDS Return Management

Quarterly TDS Return Status

Section Wise TDS Payments


TDS Notice Management

TDS Notices PDF Downloads

TDS Notices Replies Attachments PDF Downloads


Click here for updated pricing: https://www.easycloudbooks.com/ 


Thank you for being a valued customer.



For more support:

Contact: +91 99747 75018

Support email: [support@easycloudbooks.com](mailto:support@easycloudbooks.com) 

Web: https://www.easycloudbooks.com/ 

Thanks & Regards
Support Team,
